---
title: "An example of using zipfs on a directory of books"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{many-books}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE # since package isn't written yet
)
```

```{r setup}
library(zipfs)
library(tibble)
library(dplyr)
library(readr)
library(tidyr)
library(purrr)
```

The package zipfs provides a collection of texts downloaded from Gutenberg in the `extdata/` folder:
```{r}
zipfs_data_dir <- system.file("extdata", package = "zipfs")
books <- tibble(
  file = fs::dir_ls(zipfs_data_dir, glob = "*.txt")
)
books
```

Read in the all lines of each and get book meta data:
```{r}
books <- 
  books %>% 
  rowwise(file) %>% 
  mutate(text = list(read_lines(file))) 

books_summaries <- 
  books %>% 
  summarise(book_meta(text[1:20]), .groups = "rowwise")
book_summaries
```

Count words in each book:
```{r}
word_freqs <- books %>% 
  rowwise(file) %>% 
  summarise(count_words(text))
word_freqs
```

Estimate the power law parameter for each book:
```{r}
word_freqs %>% 
  group_by(file) %>% 
  summarise(alpha = fit_zipfs(n)) %>% 
  arrange(alpha)
```
Create rank plots for each book, 
THIS DOESN'T WORK
```{r, error = TRUE}
zipfs_plots <- word_freqs %>% 
  summarise(plot = list(plot_rank(n)))
zipfs_plots$plot[[1]]
```


```{r, error = TRUE}
zipfs_plots <- word_freqs %>% 
  group_by(file) %>% 
  nest(data = c(word, n)) %>% 
  rowwise() %>% 
  mutate(plot = list(plot_rank(data$n)))
zipfs_plots$plot[[1]]
```

```{r}
tmp <- word_freqs %>% 
  group_by(file) %>% 
  nest(data = c(word, n))
plot_rank(tmp$data[[1]]$n)
```

purrr approach
```{r}
zipfs_plots <- word_freqs %>% 
  group_by(file) %>% 
  nest(data = c(word, n)) %>% 
  mutate(plot = map(data, ~ plot_rank(.$n, add_fit = TRUE)))
walk(zipfs_plots$plot, print)
```

